### ISSUE TITLE
Building an image out of the generated ISO or installed VDI

### ISSUE THREAD

**Issue by robertoandrade** [Aerath/Docker-Android-x86#1]
Would there be a way to gene ate a docker image with the outcome of the build process (i.e.: either the Android x86 ISO or the result of installing the ISO into a VDI/IMG)?

**Comment by Aerath** [comment]
What do you want exactly ? A docker container running by itself, like automated builds does, or you will have access to a shell ?

Automated installation of OS is almost impossible, as it is dialog-based (by default. I don't know if there is an option or something to achieve it, like giving all configuration information in a command-line.

Even if you have a shell, I don't think that you could easily make Docker install Android-x86 : you could run a virtual machine (like qemu)  inside the docker container and use that hypothetic command-line to install it in any virtual drive file. But you will only get a docker container with Ubuntu OS and a virtual drive with Android OS, wich make half the data stored useless for Android and no direct acess to the virtual drive. And most important : running a docker container, which run a virtual machine like qemu, that run a computer installing an OS will use a lot of memory and process speed.

**Comment by Aerath** [comment]
And I should warn you that this is only  an experiment : this repo is public to share ideas, not for the open-source ability of Github.

**Comment by robertoandrade** [comment]
Ok, I guess my question was misleading... what I'm wondering is, ok cool, I have an Android-x86-dev container image, which is what this project is about and I can build the binaries for Android-x86.

Now, if I were to (not necessarily automatically) build a new docker image based on the results (the ISO or even the finally installed OS - by tarring it etc) of this Android x86 build (I could download the build as well, doesn't need to come out of the other container).

So wondering if you had any experiencing in building these base images (in this case based on a Android x86 build).

**Comment by Aerath** [comment]
I'm not english, so it is possible I missed some points in your  question but again, I'm not sure to fully understand you : did you mean Docker base images ?
If that's it ; no, not at all. I mostly use Docker for remote builds (when I work on a computer without needed toolchain like at my university), wich end in awkward commit log.

And sorry for delayed answer but as I previously said I am very busy with other projects and upcoming exams.

**Comment by robertoandrade** [comment]
Ok, no problem. Nevermind, I just thought maybe you had some extra experience in building base images and could give me some pointers to building one with the results of the build. Thanks anyways ;)
