### ISSUE TITLE
Partially built image published to Docker Hub Registry

### ISSUE THREAD

**Issue by robertoandrade** [Aerath/Docker-Android-x86#2]
I forked the project to modify a few things in the `Dockerfile` in order to build an image and ended up noticing this would take a lot more time and space than I anticipated. So I partially built the image just pull ing the sources but not compiling anything and uploaded the result to the [Docker Hub Registry](https://registry.hub.docker.com/u/robertoandrade/docker-android-x86/) so other people can fetch it instead of trying to do this over.

You may find my fork at https://github.com/robertoandrade/Docker-Android-x86 and pull the built image via:

```
docker pull robertoandrade/docker-android-x86:kitkat
```

**Comment by Aerath** [comment]
I'm very busy currently, but I will examine this ASAP. Nice to see this repo becoming a bit more usefull.
